FROM apache/spark-py:v3.3.2

# give worker permission to do file stuff
USER root

# another built in worker start up script, but need to pass master url
CMD ["/opt/spark/sbin/start-worker.sh", "spark://master:7077"]
